apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jvb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/jitsi-docker-default: "true"
        io.kompose.service: jvb
    spec:
      containers:
        - env:
            - name: DOCKER_HOST_ADDRESS
              value: https://172.25.248.11:8443
            - name: JVB_AUTH_PASSWORD
              value: 6fb2d59bb4bd3dbc9534d1713baf19da
            - name: JVB_PORT
              value: "30300"
            - name: PUBLIC_URL
              value: https://172.25.248.11:8443
            - name: SENTRY_DSN
              value: '"0"'
            - name: TZ
              value: UTC
            - name: XMPP_SERVER
              value: prosody
          image: jitsi/jvb:stable-8960-1
          name: jvb
          ports:
            - containerPort: 30300
              hostPort: 30300
              protocol: UDP
            - containerPort: 8080
              hostIP: 127.0.0.1
              hostPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
