apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  ports:
    - name: "30300"
      port: 30300
      protocol: UDP
      targetPort: 30300
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: jvb
status:
  loadBalancer: {}
