apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prosody
  name: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prosody
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/jitsi-docker-default: "true"
        io.kompose.service: prosody
    spec:
      containers:
        - env:
            - name: JIBRI_RECORDER_PASSWORD
              value: 7804431fe66d2ba8310e12edcb73670c
            - name: JIBRI_XMPP_PASSWORD
              value: 2df0687826796194daf363adcf2cfd39
            - name: JICOFO_AUTH_PASSWORD
              value: 4c7f01bf5042aa641efd3db9d6a3c067
            - name: JIGASI_XMPP_PASSWORD
              value: 077332e0ea57c719dda6d2363920a808
            - name: JVB_AUTH_PASSWORD
              value: 6fb2d59bb4bd3dbc9534d1713baf19da
            - name: PUBLIC_URL
              value: https://172.25.248.11:8443
            - name: TZ
              value: UTC
          image: jitsi/prosody:stable-8960-1
          name: prosody
          ports:
            - containerPort: 5222
              protocol: TCP
            - containerPort: 5347
              protocol: TCP
            - containerPort: 5280
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
