apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prosody
  name: prosody
spec:
  ports:
    - name: "5222"
      port: 5222
      targetPort: 5222
    - name: "5347"
      port: 5347
      targetPort: 5347
    - name: "5280"
      port: 5280
      targetPort: 5280
  externalIPs:
    - '172.25.248.11'
  selector:
    io.kompose.service: prosody
status:
  loadBalancer: {}
