apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  externalIPs:
    - '172.25.248.11'
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
