apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/jitsi-docker-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: PUBLIC_URL
              value: https://172.25.248.11:8443
            - name: TZ
              value: UTC
            - name: XMPP_BOSH_URL_BASE
              value: http://10.43.45.3:5280
          image: jitsi/web:stable-8960-1
          name: web
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
            - containerPort: 443
              hostPort: 8443
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
